# Spring Boot configuration
spring:
  application:
    name: vollmed
  profiles:
    active: ${APP_PROFILE:dev}
  mvc:
    locale: pt_BR # en_US
    locale-resolver: fixed
    offset: -03:00 # -05:00
# API | Personalization
api:
  profile: ${spring.profiles.active}
  system-tag: LANET-API-VOLLMED
  system-tag-base: VOLLMED.API
  system-version: v.1.0.0
  system-reference: LA.net | API Vollmed
  system-information: Vollmed
  system-description: Vollmed
  system-name: ${api.system-reference} ${api.system-version} (${api.system-tag})
  url-site: www.vollmed.com
  title-site: VOLLMED
  email-site: contato@vollmed.com
  config:
    language: ${spring.mvc.locale}
    version: v1
    path: # /api/${api.config.version}
  debug: true
  debug.debug-type: basic # full (all) | basic (dev,test)
# Server
server:
  error:
    include-stacktrace: never # always or never
# SpringDoc | Swagger
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /doc
    enabled: true
    tryItOutEnabled: true
